language: node_js
node_js:
  - 0.10
env:
  global:
    # Please get your own free key if you want to test yourself
    - BROWSERSTACK_USERNAME: sitepenlabs1
    - BROWSERSTACK_ACCESS_KEY: xm1uYrJuV3gZMJqCyZJX
script: tests/run.sh
